//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swazer.ShoppingList.WebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Swazer.ShoppingList.WebApp.Resources.Shared.SharedStrings", typeof(SharedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم قفل الحساب يرجى المحاولة لاحقا.
        /// </summary>
        public static string AccountLockedOut {
            get {
                return ResourceManager.GetString("AccountLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغعيل متعدد.
        /// </summary>
        public static string ActivateMultiple {
            get {
                return ResourceManager.GetString("ActivateMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت الإضافة بنجاح.
        /// </summary>
        public static string AddedSuccessfully {
            get {
                return ResourceManager.GetString("AddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكل.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع الحقوق محفوظة.
        /// </summary>
        public static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المواعيد.
        /// </summary>
        public static string Appointment {
            get {
                return ResourceManager.GetString("Appointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إلغاء المواعيد بنجاح.
        /// </summary>
        public static string AppointmentCancelValidation {
            get {
                return ResourceManager.GetString("AppointmentCancelValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل الموعد بنجاح.
        /// </summary>
        public static string AppointmentEditValidation {
            get {
                return ResourceManager.GetString("AppointmentEditValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم نقل الموعد بنجاح.
        /// </summary>
        public static string AppointmentMoveValidation {
            get {
                return ResourceManager.GetString("AppointmentMoveValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إضافة نتيجة الموعد بنجاح.
        /// </summary>
        public static string AppointmentResultValidation {
            get {
                return ResourceManager.GetString("AppointmentResultValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عودة.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العودة للصفحة الرئيسية.
        /// </summary>
        public static string BackToHome {
            get {
                return ResourceManager.GetString("BackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلا الجنسين.
        /// </summary>
        public static string BothOfGenders {
            get {
                return ResourceManager.GetString("BothOfGenders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بواسطة SWAZER.
        /// </summary>
        public static string BySwazer {
            get {
                return ResourceManager.GetString("BySwazer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مركز الأتصال.
        /// </summary>
        public static string CallCenters {
            get {
                return ResourceManager.GetString("CallCenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد من إلغاء الموعد؟.
        /// </summary>
        public static string CancelReservationString {
            get {
                return ResourceManager.GetString("CancelReservationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المراكز والعيادات.
        /// </summary>
        public static string CentersAndClinics {
            get {
                return ResourceManager.GetString("CentersAndClinics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تغيير كلمة المرور بنجاح.
        /// </summary>
        public static string ChangePasswordSuccessfully {
            get {
                return ResourceManager.GetString("ChangePasswordSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغير الحالة.
        /// </summary>
        public static string ChangeStatus {
            get {
                return ResourceManager.GetString("ChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل الحالة بنجاح.
        /// </summary>
        public static string ChangeStatusSuccessfully {
            get {
                return ResourceManager.GetString("ChangeStatusSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسح.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  اضغط اذا لم تستلم الرمز.
        /// </summary>
        public static string ClickCode {
            get {
                return ResourceManager.GetString("ClickCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفقة صحة.
        /// </summary>
        public static string ClinicReservation {
            get {
                return ResourceManager.GetString("ClinicReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إغلاق.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكود.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إعادة إرسال الكود الى جوالكم.
        /// </summary>
        public static string CodeResentSuccessfully {
            get {
                return ResourceManager.GetString("CodeResentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشكاوي.
        /// </summary>
        public static string Complains {
            get {
                return ResourceManager.GetString("Complains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل انت متأكد من حذف {0} ؟.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجهات والاتصالات.
        /// </summary>
        public static string ContactsAndCalls {
            get {
                return ResourceManager.GetString("ContactsAndCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقوق النشر.
        /// </summary>
        public static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشاء.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إنشاء الأجندة بنجاح.
        /// </summary>
        public static string CreateAgendaValidation {
            get {
                return ResourceManager.GetString("CreateAgendaValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إنشاء شكوى جديدة.
        /// </summary>
        public static string CreateComplainSuccessMessage {
            get {
                return ResourceManager.GetString("CreateComplainSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إنشاء ملف المريض بنجاح.
        /// </summary>
        public static string CreateUserFileSuccessMessage {
            get {
                return ResourceManager.GetString("CreateUserFileSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء تفعيل متعدد.
        /// </summary>
        public static string DeactivateMultiple {
            get {
                return ResourceManager.GetString("DeactivateMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحذف بنجاح.
        /// </summary>
        public static string DeletedSuccessfully {
            get {
                return ResourceManager.GetString("DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف متعدد.
        /// </summary>
        public static string DeleteMultiple {
            get {
                return ResourceManager.GetString("DeleteMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد من حذف {0} ؟.
        /// </summary>
        public static string DeleteMultipleConfirmation {
            get {
                return ResourceManager.GetString("DeleteMultipleConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأطباء.
        /// </summary>
        public static string Doctors {
            get {
                return ResourceManager.GetString("Doctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل الشكوى بنجاح.
        /// </summary>
        public static string EditComplainSuccessMessage {
            get {
                return ResourceManager.GetString("EditComplainSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التعديل بنجاح.
        /// </summary>
        public static string EditedSuccessfully {
            get {
                return ResourceManager.GetString("EditedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل فرد العائلة بنجاح.
        /// </summary>
        public static string EditFamilyMemberSuccessMessage {
            get {
                return ResourceManager.GetString("EditFamilyMemberSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عناصر.
        /// </summary>
        public static string Elements {
            get {
                return ResourceManager.GetString("Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم ارسال الايميل بنجاح.
        /// </summary>
        public static string EmailSendSuccessMessage {
            get {
                return ResourceManager.GetString("EmailSendSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل معلومات للتفعيل.
        /// </summary>
        public static string EnterDataToEnable {
            get {
                return ResourceManager.GetString("EnterDataToEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ.
        /// </summary>
        public static string Error_HeaderTitle {
            get {
                return ResourceManager.GetString("Error_HeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان الخطأ.
        /// </summary>
        public static string Error_MessageTitle {
            get {
                return ResourceManager.GetString("Error_MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف فرد العائلة بنجاح.
        /// </summary>
        public static string FamilyMemberSuccessDelete {
            get {
                return ResourceManager.GetString("FamilyMemberSuccessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتهى الوقت.
        /// </summary>
        public static string FinishedTimeCode {
            get {
                return ResourceManager.GetString("FinishedTimeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجمعة.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفقة صحة.
        /// </summary>
        public static string HealthDeal {
            get {
                return ResourceManager.GetString("HealthDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هنا.
        /// </summary>
        public static string Here {
            get {
                return ResourceManager.GetString("Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرحبا.
        /// </summary>
        public static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصفحة الرئيسية.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير فعال.
        /// </summary>
        public static string InActive {
            get {
                return ResourceManager.GetString("InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللغات.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقفل.
        /// </summary>
        public static string LockedOut {
            get {
                return ResourceManager.GetString("LockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل خروج.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفعيل.
        /// </summary>
        public static string MakeActive {
            get {
                return ResourceManager.GetString("MakeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء تفعيل.
        /// </summary>
        public static string MakeDeactivate {
            get {
                return ResourceManager.GetString("MakeDeactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديد الافتراضي.
        /// </summary>
        public static string MakeDefault {
            get {
                return ResourceManager.GetString("MakeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدقائق.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأثنين.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لايوجد اختيار.
        /// </summary>
        public static string NoAction {
            get {
                return ResourceManager.GetString("NoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد بيانات مطابقة لمعايير البحث.
        /// </summary>
        public static string NoItemsResult {
            get {
                return ResourceManager.GetString("NoItemsResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد بيانات مطابقة لمعاير البحث.
        /// </summary>
        public static string NoResult {
            get {
                return ResourceManager.GetString("NoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المصدر غير موجود.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخيارات.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأول.
        /// </summary>
        public static string PagerList_First {
            get {
                return ResourceManager.GetString("PagerList_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأخير.
        /// </summary>
        public static string PagerList_Last {
            get {
                return ResourceManager.GetString("PagerList_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التالي.
        /// </summary>
        public static string PagerList_Next {
            get {
                return ResourceManager.GetString("PagerList_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السابق.
        /// </summary>
        public static string PagerList_Previous {
            get {
                return ResourceManager.GetString("PagerList_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الهاتف.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملفي الشخصي.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنشورات.
        /// </summary>
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوقت المتبقي للكود.
        /// </summary>
        public static string RemainingTimeCode {
            get {
                return ResourceManager.GetString("RemainingTimeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لإعادة إرسال الرمز إلى هاتفك .
        /// </summary>
        public static string ResendTheCode {
            get {
                return ResourceManager.GetString("ResendTheCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خصائص الحجوزات.
        /// </summary>
        public static string Reservation {
            get {
                return ResourceManager.GetString("Reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السبت.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر كل الشكاوي.
        /// </summary>
        public static string SelectAllComplain {
            get {
                return ResourceManager.GetString("SelectAllComplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كل حالات الشكاوي.
        /// </summary>
        public static string SelectAllComplainStatuses {
            get {
                return ResourceManager.GetString("SelectAllComplainStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كل أنواع الشكاوي.
        /// </summary>
        public static string SelectAllComplainTypes {
            get {
                return ResourceManager.GetString("SelectAllComplainTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلا الجنسين.
        /// </summary>
        public static string SelectAllGender {
            get {
                return ResourceManager.GetString("SelectAllGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كل حالات النشر.
        /// </summary>
        public static string SelectAllPublishingStatus {
            get {
                return ResourceManager.GetString("SelectAllPublishingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كل حالات الحجز.
        /// </summary>
        public static string SelectAllReservationStatuses {
            get {
                return ResourceManager.GetString("SelectAllReservationStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر كل حالات الرد.
        /// </summary>
        public static string SelectAllResponseStatus {
            get {
                return ResourceManager.GetString("SelectAllResponseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كل الحالات.
        /// </summary>
        public static string SelectAllStatus {
            get {
                return ResourceManager.GetString("SelectAllStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر.
        /// </summary>
        public static string SelectPlaceholder {
            get {
                return ResourceManager.GetString("SelectPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأحصائيات.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأحد.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخميس.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الثلاثاء.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدراج صورة.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمين والصلاحيات.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأربعاء.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرحبا بك في إدارة المواعيد.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
