//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swazer.ShoppingList.SqlServerRepository {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RepositoryResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RepositoryResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Swazer.ShoppingList.SqlServerRepository.RepositoryResource", typeof(RepositoryResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo_AgendaConfigurationItems.
        /// </summary>
        internal static string dbo_AgendaConfigurationItems {
            get {
                return ResourceManager.GetString("dbo_AgendaConfigurationItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo_AgendaConfigurations.
        /// </summary>
        internal static string dbo_AgendaConfigurations {
            get {
                return ResourceManager.GetString("dbo_AgendaConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo_AppointmentPeriods.
        /// </summary>
        internal static string dbo_AppointmentPeriods {
            get {
                return ResourceManager.GetString("dbo_AppointmentPeriods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo_AppointmentsCounts.
        /// </summary>
        internal static string dbo_AppointmentsCounts {
            get {
                return ResourceManager.GetString("dbo_AppointmentsCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo_AttachmentFiles.
        /// </summary>
        internal static string dbo_AttachmentFiles {
            get {
                return ResourceManager.GetString("dbo_AttachmentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo_Attachments.
        /// </summary>
        internal static string dbo_Attachments {
            get {
                return ResourceManager.GetString("dbo_Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo_Complain.
        /// </summary>
        internal static string dbo_Complain {
            get {
                return ResourceManager.GetString("dbo_Complain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo_ComplainStatuses.
        /// </summary>
        internal static string dbo_ComplainStatuses {
            get {
                return ResourceManager.GetString("dbo_ComplainStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo_ComplainType.
        /// </summary>
        internal static string dbo_ComplainType {
            get {
                return ResourceManager.GetString("dbo_ComplainType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo_ContactInformations.
        /// </summary>
        internal static string dbo_ContactInformations {
            get {
                return ResourceManager.GetString("dbo_ContactInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo_ContactRegions.
        /// </summary>
        internal static string dbo_ContactRegions {
            get {
                return ResourceManager.GetString("dbo_ContactRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo_ContactTypes.
        /// </summary>
        internal static string dbo_ContactTypes {
            get {
                return ResourceManager.GetString("dbo_ContactTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo_ContentList.
        /// </summary>
        internal static string dbo_ContentList {
            get {
                return ResourceManager.GetString("dbo_ContentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo_CoversationDetails.
        /// </summary>
        internal static string dbo_CoversationDetails {
            get {
                return ResourceManager.GetString("dbo_CoversationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo_Coversations.
        /// </summary>
        internal static string dbo_Coversations {
            get {
                return ResourceManager.GetString("dbo_Coversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo_DoctorContractTypes.
        /// </summary>
        internal static string dbo_DoctorContractTypes {
            get {
                return ResourceManager.GetString("dbo_DoctorContractTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo_Doctors.
        /// </summary>
        internal static string dbo_Doctors {
            get {
                return ResourceManager.GetString("dbo_Doctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo_FamilyMembers.
        /// </summary>
        internal static string dbo_FamilyMembers {
            get {
                return ResourceManager.GetString("dbo_FamilyMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo_Leaves.
        /// </summary>
        internal static string dbo_Leaves {
            get {
                return ResourceManager.GetString("dbo_Leaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo_LeaveTypes.
        /// </summary>
        internal static string dbo_LeaveTypes {
            get {
                return ResourceManager.GetString("dbo_LeaveTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo_MedicalArticles.
        /// </summary>
        internal static string dbo_MedicalArticles {
            get {
                return ResourceManager.GetString("dbo_MedicalArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo_MedicalCenterCategories.
        /// </summary>
        internal static string dbo_MedicalCenterCategories {
            get {
                return ResourceManager.GetString("dbo_MedicalCenterCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo_MedicalCenters.
        /// </summary>
        internal static string dbo_MedicalCenters {
            get {
                return ResourceManager.GetString("dbo_MedicalCenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo_MedicalClinics.
        /// </summary>
        internal static string dbo_MedicalClinics {
            get {
                return ResourceManager.GetString("dbo_MedicalClinics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo_MedicalVisitReasons.
        /// </summary>
        internal static string dbo_MedicalVisitReasons {
            get {
                return ResourceManager.GetString("dbo_MedicalVisitReasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo_Nationalities.
        /// </summary>
        internal static string dbo_Nationalities {
            get {
                return ResourceManager.GetString("dbo_Nationalities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo_NewsItems.
        /// </summary>
        internal static string dbo_NewsItems {
            get {
                return ResourceManager.GetString("dbo_NewsItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo_Offers.
        /// </summary>
        internal static string dbo_Offers {
            get {
                return ResourceManager.GetString("dbo_Offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo_Photos.
        /// </summary>
        internal static string dbo_Photos {
            get {
                return ResourceManager.GetString("dbo_Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo_Regions.
        /// </summary>
        internal static string dbo_Regions {
            get {
                return ResourceManager.GetString("dbo_Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo_ReservationNumbers.
        /// </summary>
        internal static string dbo_ReservationNumbers {
            get {
                return ResourceManager.GetString("dbo_ReservationNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo_Reservations.
        /// </summary>
        internal static string dbo_Reservations {
            get {
                return ResourceManager.GetString("dbo_Reservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo_UserFiles.
        /// </summary>
        internal static string dbo_UserFiles {
            get {
                return ResourceManager.GetString("dbo_UserFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo_Videos.
        /// </summary>
        internal static string dbo_Videos {
            get {
                return ResourceManager.GetString("dbo_Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo_WorkHours.
        /// </summary>
        internal static string dbo_WorkHours {
            get {
                return ResourceManager.GetString("dbo_WorkHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo_WorkPeriods.
        /// </summary>
        internal static string dbo_WorkPeriods {
            get {
                return ResourceManager.GetString("dbo_WorkPeriods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The validation Rules must be satisfied..
        /// </summary>
        internal static string ErrorException_ModelValidation {
            get {
                return ResourceManager.GetString("ErrorException_ModelValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Server Name is not correct or is not accessible..
        /// </summary>
        internal static string ErrorMessage_ConnectionFailed {
            get {
                return ResourceManager.GetString("ErrorMessage_ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Entity has been updated by another user, please refresh the browser and try again..
        /// </summary>
        internal static string ErrorMessage_DbUpdateConcurrency {
            get {
                return ResourceManager.GetString("ErrorMessage_DbUpdateConcurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} must not be duplicated..
        /// </summary>
        internal static string ErrorMessage_DuplicatedValue {
            get {
                return ResourceManager.GetString("ErrorMessage_DuplicatedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لايمكن حذف هذا العنصر لأن هناك عناصر أخرى تعتمد عليه.
        /// </summary>
        internal static string ErrorMessage_GeneralDependency {
            get {
                return ResourceManager.GetString("ErrorMessage_GeneralDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل في الاتصال مع قاعدة البيانات الرجاء المحاولة لاحقا.
        /// </summary>
        internal static string ErrorMessage_GeneralError {
            get {
                return ResourceManager.GetString("ErrorMessage_GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while Authentication with the Database Server..
        /// </summary>
        internal static string ErrorMessage_LogingFailed {
            get {
                return ResourceManager.GetString("ErrorMessage_LogingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete because {0} is depending on {1} , which you are deleting..
        /// </summary>
        internal static string ErrorMessage_TwoEntityDependency {
            get {
                return ResourceManager.GetString("ErrorMessage_TwoEntityDependency", resourceCulture);
            }
        }
    }
}
