//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swazer.ShoppingList.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CoreStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Swazer.ShoppingList.Core.CoreStrings", typeof(CoreStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emailini doğrula ve öğrenmeye başla.
        /// </summary>
        public static string ConfirmEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email doğrulama işlemi başarısız.
        /// </summary>
        public static string ConfirmEmailIncorrect {
            get {
                return ResourceManager.GetString("ConfirmEmailIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merhaba, size bu emaili gönderdik, çünkü email adresiniz Üstad Uygulamasına kaydolmak için kullanıldı. Lütfen kaydolma işlemini tamamlamak için aşağıdaki linke tıklayınız.
        /// </summary>
        public static string ConfirmEmailRegister {
            get {
                return ResourceManager.GetString("ConfirmEmailRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eğer Ustad Uygulamasına kaydolmadıysanız, linke tıklamayınız ve bu mesajı dikkate almayınız.
        /// </summary>
        public static string IfYouDidntRequestForRegister {
            get {
                return ResourceManager.GetString("IfYouDidntRequestForRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eğer Ustad Uygulamasına üye değilseniz linke tıklamayınız ve bu mesajı dikkate almayınız.
        /// </summary>
        public static string IfYouDidntRequestForReset {
            get {
                return ResourceManager.GetString("IfYouDidntRequestForReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merhaba, size bu emaili gönderdik, çünkü email adresiniz Üstad Uygulaması şifrenizi sıfırlamak için kullanıldı. Lütfen şifrenizi sıfırlamak için aşağıdaki kodu kullanınız.
        /// </summary>
        public static string IfYouHaveLostYourPassword {
            get {
                return ResourceManager.GetString("IfYouHaveLostYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekleme talebinde bulunduğunuz {0} isimli konu site yöneticisi tarafından kabul edildi..
        /// </summary>
        public static string NewSubjectAccepted {
            get {
                return ResourceManager.GetString("NewSubjectAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konu Ekleme Onayı.
        /// </summary>
        public static string NewSubjectAcceptedTitle {
            get {
                return ResourceManager.GetString("NewSubjectAcceptedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Konu Talebi.
        /// </summary>
        public static string NewSubjectAddedTitle {
            get {
                return ResourceManager.GetString("NewSubjectAddedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu işlem için izniniz yok.
        /// </summary>
        public static string NoPermission {
            get {
                return ResourceManager.GetString("NoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulunamadı.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üstad.
        /// </summary>
        public static string ResetPasswordFrom {
            get {
                return ResourceManager.GetString("ResetPasswordFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üstad Şifre Sıfırlama.
        /// </summary>
        public static string ResetPasswordHeader {
            get {
                return ResourceManager.GetString("ResetPasswordHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreni Sıfırla.
        /// </summary>
        public static string ResetPasswordTitle {
            get {
                return ResourceManager.GetString("ResetPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} mail adresine sahip kullanıcı tarafından {1} isimli ders için ekleme talebinde bulunuldu..
        /// </summary>
        public static string SubjectAddedInfo {
            get {
                return ResourceManager.GetString("SubjectAddedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üstad Hesabınız.
        /// </summary>
        public static string UstadAccount {
            get {
                return ResourceManager.GetString("UstadAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydolmayı Tamamlayın.
        /// </summary>
        public static string UstadRegistration {
            get {
                return ResourceManager.GetString("UstadRegistration", resourceCulture);
            }
        }
    }
}
