//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swazer.ShoppingList.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CoreStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Swazer.ShoppingList.Core.CoreStrings", typeof(CoreStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأدمين.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشرف مركز.
        /// </summary>
        public static string CenterSupervisor {
            get {
                return ResourceManager.GetString("CenterSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موظف عيادة.
        /// </summary>
        public static string ClinicEmployee {
            get {
                return ResourceManager.GetString("ClinicEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مركز الإتصال.
        /// </summary>
        public static string CommunicationCenter {
            get {
                return ResourceManager.GetString("CommunicationCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت الأفادة.
        /// </summary>
        public static string ComplainStatus_Done {
            get {
                return ResourceManager.GetString("ComplainStatus_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شكوى جديدة.
        /// </summary>
        public static string ComplainStatus_New {
            get {
                return ResourceManager.GetString("ComplainStatus_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Arabic.
        /// </summary>
        public static string ComplainStatus_Processing {
            get {
                return ResourceManager.GetString("ComplainStatus_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الايميل.
        /// </summary>
        public static string ContactTypeEnum_Email {
            get {
                return ResourceManager.GetString("ContactTypeEnum_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string ContactTypeEnum_FaxAddress {
            get {
                return ResourceManager.GetString("ContactTypeEnum_FaxAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الهاتف.
        /// </summary>
        public static string ContactTypeEnum_Phone {
            get {
                return ResourceManager.GetString("ContactTypeEnum_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان البريد الالكتروني.
        /// </summary>
        public static string ContactTypeEnum_WebAddress {
            get {
                return ResourceManager.GetString("ContactTypeEnum_WebAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حول.
        /// </summary>
        public static string ContentListType_AboutUs {
            get {
                return ResourceManager.GetString("ContentListType_AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شركات التأمين.
        /// </summary>
        public static string ContentListType_AssuranceCompany {
            get {
                return ResourceManager.GetString("ContentListType_AssuranceCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتصل بنا.
        /// </summary>
        public static string ContentListType_ContactUs {
            get {
                return ResourceManager.GetString("ContentListType_ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأسئلة المتكرة.
        /// </summary>
        public static string ContentListType_FAQ {
            get {
                return ResourceManager.GetString("ContentListType_FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المكز الإعلامي.
        /// </summary>
        public static string ContentListType_MediaCenter {
            get {
                return ResourceManager.GetString("ContentListType_MediaCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمة المرضى.
        /// </summary>
        public static string ContentListType_PatientService {
            get {
                return ResourceManager.GetString("ContentListType_PatientService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخدمات الشخصية.
        /// </summary>
        public static string ContentListType_PersonalService {
            get {
                return ResourceManager.GetString("ContentListType_PersonalService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساسية الخصوصية.
        /// </summary>
        public static string ContentListType_PrivacyPolicy {
            get {
                return ResourceManager.GetString("ContentListType_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عطلة.
        /// </summary>
        public static string DayType_Vacation {
            get {
                return ResourceManager.GetString("DayType_Vacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عمل.
        /// </summary>
        public static string DayType_Work {
            get {
                return ResourceManager.GetString("DayType_Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابن - ابنة.
        /// </summary>
        public static string FamilyRelation_Son {
            get {
                return ResourceManager.GetString("FamilyRelation_Son", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زوجة.
        /// </summary>
        public static string FamilyRelation_Wife {
            get {
                return ResourceManager.GetString("FamilyRelation_Wife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنثى.
        /// </summary>
        public static string Gender_Female {
            get {
                return ResourceManager.GetString("Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذكر.
        /// </summary>
        public static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لاتملك الصلاحيات الكافية.
        /// </summary>
        public static string NoPermission {
            get {
                return ResourceManager.GetString("NoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنصر المطلوب غير موجود.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ليس للنشر.
        /// </summary>
        public static string PublishingStatus_NotPublish {
            get {
                return ResourceManager.GetString("PublishingStatus_NotPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشر.
        /// </summary>
        public static string PublishingStatus_Publish {
            get {
                return ResourceManager.GetString("PublishingStatus_Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملغى.
        /// </summary>
        public static string ReservationStatus_Canceled {
            get {
                return ResourceManager.GetString("ReservationStatus_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شاغر.
        /// </summary>
        public static string ReservationStatus_Empty {
            get {
                return ResourceManager.GetString("ReservationStatus_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moved.
        /// </summary>
        public static string ReservationStatus_Moved {
            get {
                return ResourceManager.GetString("ReservationStatus_Moved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مؤكد.
        /// </summary>
        public static string ReservationStatus_Sure {
            get {
                return ResourceManager.GetString("ReservationStatus_Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير مكتمل.
        /// </summary>
        public static string ReservationStatus_UnCompleted {
            get {
                return ResourceManager.GetString("ReservationStatus_UnCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستخدم.
        /// </summary>
        public static string ReservationStatus_Used {
            get {
                return ResourceManager.GetString("ReservationStatus_Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء الضغط &lt;a href=&apos;{0}&apos;&gt;هنا&lt;/a&gt; لإعادة ضبط كلمة المرور الخاصة بك.
        /// </summary>
        public static string ResetPasswordEmail {
            get {
                return ResourceManager.GetString("ResetPasswordEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفقة صحة.
        /// </summary>
        public static string ResetPasswordFrom {
            get {
                return ResourceManager.GetString("ResetPasswordFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعادة ضبط كلمة المرور.
        /// </summary>
        public static string ResetPasswordTitle {
            get {
                return ResourceManager.GetString("ResetPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستخدم.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفترة المسائية.
        /// </summary>
        public static string WorkPeriodKind_Evening {
            get {
                return ResourceManager.GetString("WorkPeriodKind_Evening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفترة الصباحية.
        /// </summary>
        public static string WorkPeriodKind_Morning {
            get {
                return ResourceManager.GetString("WorkPeriodKind_Morning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفترة المسائية.
        /// </summary>
        public static string WorkPeriodKind_Night {
            get {
                return ResourceManager.GetString("WorkPeriodKind_Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فترة استراحة.
        /// </summary>
        public static string WorkPeriodType_RestTime {
            get {
                return ResourceManager.GetString("WorkPeriodType_RestTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فترة عمل.
        /// </summary>
        public static string WorkPeriodType_WorkTime {
            get {
                return ResourceManager.GetString("WorkPeriodType_WorkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
